// README.md のサービス一覧表を services.ts (単一の真実) から自動生成する。
//
// 手で表を書くと数 (45) や項目がすぐドリフトする (実際 22 のまま放置されていた)。
// マーカー間を機械生成にして、`--check` を CI に入れることでドリフトを構造的に防ぐ。
//
// 使い方:
//   node scripts/sync-readme.cjs           # README を再生成して書き込む
//   node scripts/sync-readme.cjs --check    # 同期済みか検査 (差分あれば exit 1)

const fs = require('node:fs');
const path = require('node:path');
const { ROOT, CATEGORY_LABEL, CATEGORY_ORDER, parseServices } = require('./lib/services.cjs');

const README = path.join(ROOT, 'README.md');
const START = '<!-- SERVICES:START (auto-generated by scripts/sync-readme.cjs — do not edit by hand) -->';
const END = '<!-- SERVICES:END -->';

/** services.ts からカテゴリ別のサービス一覧表 (Markdown) を生成。 */
function buildBlock() {
  const services = parseServices();
  const rows = CATEGORY_ORDER.map((cat) => {
    const items = services.filter((s) => s.category === cat);
    const labels = items.map((s) => s.label).join(' / ');
    return `| **${CATEGORY_LABEL[cat]}** (${items.length}) | ${labels} |`;
  });
  return [
    `## サービス一覧 (${services.length})`,
    '',
    '| カテゴリ | サービス |',
    '|---|---|',
    ...rows,
  ].join('\n');
}

function render(readme, block) {
  const s = readme.indexOf(START);
  const e = readme.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    throw new Error(`README.md に ${START} / ${END} マーカーが見つかりません`);
  }
  return readme.slice(0, s + START.length) + '\n' + block + '\n' + readme.slice(e);
}

function main() {
  const check = process.argv.includes('--check');
  const readme = fs.readFileSync(README, 'utf8');
  const next = render(readme, buildBlock());
  if (check) {
    if (next !== readme) {
      console.error('❌ README のサービス一覧が services.ts と不一致です。');
      console.error('   `npm run sync:readme` を実行してコミットしてください。');
      process.exit(1);
    }
    console.log('✅ README のサービス一覧は services.ts と同期しています');
    return;
  }
  fs.writeFileSync(README, next);
  console.log('✅ README のサービス一覧を services.ts から再生成しました');
}

main();
